#!/bin/bash

# Autor: caruazu
# Data: 2024-09-25

# Habilita a saída em caso de erro
set -e

# Captura a interrupção do script
trap 'echo "Interrupção detectada. Finalizando..."; exit 1' SIGINT SIGTERM

# Carrega as credenciais do arquivo .env
ENV_FILE="$HOME/caruazu-scripts/.env"

# Verifica se o arquivo .env existe
if [ ! -f "$ENV_FILE" ]; then
  echo "Erro: Arquivo .env não encontrado em $ENV_FILE"
  exit 1
fi

# Carrega as variáveis de ambiente a partir do arquivo .env
source "$ENV_FILE"

# Verifica se as variáveis necessárias estão definidas
if [ -z "$DEPLOY_SPRING_SSH_USER" ] || [ -z "$DEPLOY_SPRING_SSH_PASS" ] || [ -z "$DEPLOY_SPRING_SSH_PORT" ] || [ -z "$DEPLOY_SPRING_PROJECT_NAME" ] || [ -z "$DEPLOY_SPRING_REMOTE_HOST" ]; then
  echo "Erro: Variáveis DEPLOY_SPRING_SSH_USER, DEPLOY_SPRING_SSH_PASS, DEPLOY_SPRING_SSH_PORT, DEPLOY_SPRING_PROJECT_NAME OU DEPLOY_SPRING_REMOTE_HOST não definidas no arquivo .env"
  exit 1
fi

REMOTE_HOST="$DEPLOY_SPRING_REMOTE_HOST"
SSH_USER="$DEPLOY_SPRING_SSH_USER"
SSH_PASS="$DEPLOY_SPRING_SSH_PASS"
SSH_PORT="$DEPLOY_SPRING_SSH_PORT"
PROJECT_NAME="$DEPLOY_SPRING_PROJECT_NAME"

REMOTE_FILE="/home/$SSH_USER/acesso.txt"
LOCAL_FILE="./$PROJECT_NAME.jar"
REMOTE_DESTINATION="/home/$SSH_USER/$PROJECT_NAME.jar"
FINAL_DESTINATION="/opt/$PROJECT_NAME/$PROJECT_NAME.jar"

echo "Conectando à máquina $REMOTE_HOST na porta $SSH_PORT..."


## Passo 1 ##

# Verifica se o arquivo app.jar existe no local
if [ ! -f "$LOCAL_FILE" ]; then
  echo "Erro: Arquivo $LOCAL_FILE não encontrado no diretório atual."
  exit 1
fi

# Move o arquivo app.jar para a máquina remota
echo "Enviando arquivo $LOCAL_FILE para a máquina remota..."
sshpass -p "$SSH_PASS" scp -P "$SSH_PORT" "$LOCAL_FILE" "$SSH_USER@$REMOTE_HOST:$REMOTE_DESTINATION"


## Passo 2 ##

# Comando para verificar se o arquivo já existe, mover se não existir, e reiniciar o serviço
CMD_MOVE_APP=$(cat <<EOF
  if [ -f "$FINAL_DESTINATION" ]; then
    echo 'O arquivo $FINAL_DESTINATION já existe. Removendo ele.'
    echo "$SSH_PASS" | sudo -S rm -rf $FINAL_DESTINATION
    echo -e '\n'
  fi
    echo 'Movendo arquivo para $FINAL_DESTINATION'
    echo -e '\n'
    echo "$SSH_PASS" | sudo -S mv $REMOTE_DESTINATION $FINAL_DESTINATION
EOF
)

# Executa o comando na máquina remota
echo "Verificando e movendo arquivo se necessário..."
sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$REMOTE_HOST" "$CMD_MOVE_APP"


## Passo 3 ##

# Comando para verificar se o arquivo já existe, mover se não existir, e reiniciar o serviço
RESTART_SERVICE=$(cat <<EOF
  echo "$SSH_PASS" | sudo -S systemctl restart "$PROJECT_NAME".service
  echo -e '\n'
EOF
)

# Executa o comando na máquina remota
echo "reiniciando o serviço $PROJECT_NAME..."
sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$REMOTE_HOST" "$RESTART_SERVICE"

echo "Processo concluído com sucesso!"
