import = [
  # uncomment the flavour you want below:
  # ".config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[shell]
program = "/usr/bin/tmux"
args = ["new-session"]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
opacity = 1

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 10
y = 10

[font]
size = 10

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"